# Generated by Django 4.0.5 on 2022-06-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('latitude', models.CharField(max_length=255, verbose_name='北緯')),
                ('longitude', models.CharField(max_length=255, verbose_name='東経')),
                ('address', models.CharField(max_length=255, verbose_name='所在地')),
            ],
        ),
        migrations.AlterField(
            model_name='src',
            name='src',
            field=models.CharField(max_length=255, verbose_name='出発地'),
        ),
    ]
