# Generated by Django 4.0.5 on 2022-06-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0002_dest_alter_src_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='geoCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255, verbose_name='出発地')),
                ('latitude', models.CharField(max_length=255, verbose_name='北緯')),
                ('longitude', models.CharField(max_length=255, verbose_name='東経')),
            ],
        ),
        migrations.CreateModel(
            name='routeCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=255, verbose_name='出発地')),
                ('dest', models.CharField(max_length=255, verbose_name='目的地')),
                ('highway', models.CharField(max_length=255, verbose_name='高速')),
                ('localway', models.CharField(max_length=255, verbose_name='下道')),
            ],
        ),
    ]
